import React from 'react';
import { FileText, Download } from 'lucide-react';
import SearchableWrapper from '../../../components/Searchbar/SearchableWrapper';

export default function IprPolicy() {
  return (
    <SearchableWrapper>
      <div className="bg-white rounded-2xl p-6 sm:p-10 border border-gray-100 shadow-sm space-y-10">
        {/* GBU IPR Policy */}
        <div>
          <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-1">
            GBU IPR Policy
          </h2>
          <div className="h-1 w-20 bg-amber-500 rounded-full mb-6"></div>

          <p className="text-gray-700 text-base leading-relaxed bg-slate-50 p-4 rounded-xl border-l-4 border-amber-500">
            <strong>'Inventor'</strong> means any employee of Gautam Buddha University (GBU) directly and/or indirectly associated and includes those who are faculty and his/her research team members.
          </p>
        </div>

        {/* Patent Filing */}
        <div>
          <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-1">
            Patent Filling
          </h2>
          <div className="h-1 w-20 bg-amber-500 rounded-full mb-6"></div>

          <ul className="list-disc pl-6 space-y-3 text-gray-700 text-base leading-relaxed">
            <li>
              The University faculty who wishes to file a patent application would submit an application along with requisite document to the Patent cell.
            </li>
            <li>
              The University may authorize the inventor(s) as applicant to file the patent. The financial expenses will be borne by the inventor(s). All the legal and financial liabilities will lie with the inventor(s).
            </li>
            <li>
              The University may also authorize the inventor(s) to get the patent filed through funding agencies such as DBT, NRDC and DST (TIFAC) on case by case basis.
            </li>
            <li>
              Any work sought to be filed for IPR by a faculty member alongwith his/her team members arising out of R&D work done at the University will required to be filed in joint names as inventors.
            </li>
            <li>
              If the IPR is a result of funds sponsored by an outside agency, then the IPR will be shared between GBU and the sponsoring agency on case by case basis, as per MOU/Agreement/Undertaking between GBU and the outside agency.
            </li>
          </ul>
        </div>

        {/* Revenue Sharing */}
        <div>
          <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-1">
            Revenue Sharing
          </h2>
          <div className="h-1 w-20 bg-amber-500 rounded-full mb-6"></div>

          <ul className="list-disc pl-6 space-y-3 text-gray-700 text-base leading-relaxed mb-6">
            <li>
              With prior approval of GBU (through Patent Cell Committee) inventor(s) should take necessary steps for commercialization of technology/material developed.
            </li>
            <li>
              Any revenue generated by the exploitation of IPR, will be shared between the inventor and University in a ratio of <strong>70:30</strong> respectively.
            </li>
          </ul>

          <div className="pt-4 border-t border-gray-100">
            <a
              href="https://gbu.ac.in/Content/gbudata/IPR/GBU_%20IPR-POLICY_12July2021.pdf"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-800 font-bold text-lg hover:underline"
            >
              <FileText className="w-5 h-5" />
              <span>GBU IPR POLICY (PDF)</span>
              <Download className="w-4 h-4 ml-1" />
            </a>
          </div>
        </div>
      </div>
    </SearchableWrapper>
  );
}
